git-2.12.0/PortableGit-2.12.0-64-bit.7z.exe:
  size: 32538592
  object_id: 2da4b813-3f84-430c-68c6-ea42743277f7
  sha: 95de9eacdbb4a3fbf3671746182e71ada0af94b1
patch-2.5.9-7/patch-2.5.9-7-bin.zip:
  size: 126248
  object_id: e9a14bf9-d600-4225-5f02-629e816aef37
  sha: 7b2ec738881f4e962e54e0f330b67c42635266b7
unzip-5.51-1/unzip.exe:
  size: 164864
  object_id: ef220abf-e90e-42a5-5e62-5b6315c01519
  sha: 0fd9a61bf9a361f87661de295e70a9c6795fe6a1
