devkit/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe:
  size: 44275037
  object_id: 4f9207e9-e7a7-42c2-68e7-ebced040b61e
  sha: cd467f4d02d60c6cf78069c59d7ff114d93426f9
git-2.12.0/PortableGit-2.12.0-64-bit.7z.exe:
  size: 32538592
  object_id: 7760fa4f-2dc0-43c3-5a2f-f652420c8a83
  sha: 95de9eacdbb4a3fbf3671746182e71ada0af94b1
gnupg-1.4.21/gnupg-w32cli-1.4.21.zip:
  size: 2899856
  object_id: d24d9de1-cbc1-45cc-4c01-9e0be845eb4b
  sha: 288e1216d942cdd64b70786ba0c820fccae30039
msys2/msys2-base-x86_64-20161025.zip:
  size: 95497849
  object_id: 47b94829-fd47-4a96-6929-b985b5383cd2
  sha: c97dfe50327bb82ac52cc97df8d5ec52ab3fbb46
patch-2.5.9-7/patch-2.5.9-7-bin.zip:
  size: 126248
  object_id: ce5c5c6c-1f92-4219-63c9-a32723ce76f5
  sha: 7b2ec738881f4e962e54e0f330b67c42635266b7
ruby-2.3/rubyinstaller-2.3.3-x64.exe:
  size: 19668866
  object_id: 1fdd0156-f14f-45db-7316-71169ca6aaa6
  sha: 83ae5e6282a2b7e21bb61c5b4d1b184c33edbd2a
ruby-2.4/rubyinstaller-2.4.2-2-x64.exe:
  size: 8982267
  object_id: 0e833881-1c65-46e6-6b5c-60cf95cd8693
  sha: c961c2752a183487bc42ed24beb7e931230fa7d5
unzip-5.51-1/unzip.exe:
  size: 164864
  object_id: 38d4557f-1c64-4e99-69f8-163d3229c8b2
  sha: 0fd9a61bf9a361f87661de295e70a9c6795fe6a1
